### PR TITLE
fix: ver4 icon

### PR DESCRIPTION
**Pull request by crowicked**
## Dework Task

https://app.dework.xyz/nation3/app-2?taskId=070b38d5-aa6a-4938-825c-99769678284f

## Related GitHub Issue

https://github.com/nation3/mobile-passport/issues/81

## How Has This Been Tested?

Not tested (no iPhone available)

- [ ] Status checks pass
- [ ] Works on Goerli
- [ ] Works on Mainnet

## Are There Admin Tasks?

No

### CODE REVIEW

**Comment by aahna-ashina** [comment]
@luisivan Will we also need `icon@3x.png`?

**Review by aahna-ashina — COMMENTED** [review]
@crowicked Could you also add `icon@3x.png`? :-D

**Review by aahna-ashina — COMMENTED** [review]
@crowicked I've spent the whole day testing on an iPhone why the icon you added does not show up.  I keep getting the old one when I send push notifications:

> IMG_0230

I've tested multiple ways, so I'm starting to believe that this is a bug in the Apple Wallet app itself, maybe a caching problem.

I say that because when I _share_ the pass, the correct icon is shown:

> IMG_0231

**Comment by crowicked** [comment]
Added icon@3x.png

**Review by aahna-ashina — APPROVED** [review]
Looks good.  And I updated the code (and unit tests) to be compatible with the 3 new icons:  https://github.com/nation3/mobile-passport/pull/93/commits/645bdcfd3794d0914b816ea6f07fdda9727936c7

**Review by johnmark13 — APPROVED** [review]

**Review by luisivan — APPROVED** [review]

**Review by okhaimie-dev — APPROVED** [review]

**Pull request merged**
