### PR TITLE
chore(): Use prettifier and eslint

### PR DESCRIPTION
**Pull request by luisivan**
Using the config files we use in the Citizen app

### CODE REVIEW

**Review by aahna-ashina — COMMENTED** [review]
@luisivan Sorry, I'm not following.  Did you run a command to trigger the code changes with prettier?  `npm run lint`?

I think I'm missing a piece of information here `¯\_ (ツ)_/¯`

**Comment by luisivan** [comment]
@aahna-ashina no, the idea with Prettier is that it's integrated with your editor (e.g. VSCode https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) and it automatically formats the file with the desired coding style on each save. It's quite cool!

**Comment by aahna-ashina** [comment]
@luisivan Okay, I hadn't installed that plugin, that's why I was so confused.

Automatically formatting code on every file save is going to be a big problem if some developers use the plugin and others don't.  So are you saying that we should ask _all_ Nation3 developers to install Visual Studio Code and the [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) plugin before committing code to our GitHub repos?  If so, let's add this piece of information to our [Contributing Guidelines](https://github.com/nation3/.github/pull/1) for Nation3 developers?

**Review by aahna-ashina — APPROVED** [review]

**Review by xPi2 — APPROVED** [review]

**Comment by luisivan** [comment]
@aahna-ashina we don't need all devs to install VSCode (which would be quite intrusive), we just need them to have some sort of integration in their development environment with Prettier. I'll do a PR to add this to the contributing guidelines

**Comment by aahna-ashina** [comment]
> @aahna-ashina we don't need all devs to install VSCode (which would be quite intrusive), we just need them to have some sort of integration in their development environment with Prettier. I'll do a PR to add this to the contributing guidelines

@luisivan Sounds good.  Then we can create a `CONTRIBUTING` document in all our repos, and all pointing to one and the same contributing guidelines, so that we only need to make updates in one location.

**Pull request merged**
